Gsl_error: improve the error reporting mechanism.
Add an error handler in the Gsl_error module. This function
get called by the GSL error handler, so that it can either raise
the Gsl_error.Gsl_exn exception or ignore the error.